runtime: python37

# Remember - storing secrets in plaintext is potentially unsafe. Consider using
# something like https://cloud.google.com/kms/ to help keep secrets secret.
env_variables:
  CLOUD_SQL_CONNECTION_NAME: artsales:us-central1:art
  DB_USER: postgres
  DB_PASS: postgres
  DB_NAME: art
